apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"e-voting-topics-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"e-voting-topics-service"}},"template":{"metadata":{"labels":{"app":"e-voting-topics-service"}},"spec":{"containers":[{"env":[{"name":"TOPICS_SERVICE","valueFrom":{"configMapKeyRef":{"key":"TOPICS_SERVICE","name":"app-config"}}},{"name":"VOTING_SERVICE","valueFrom":{"configMapKeyRef":{"key":"VOTING_SERVICE","name":"app-config"}}},{"name":"VOTERS_SERVICE","valueFrom":{"configMapKeyRef":{"key":"VOTERS_SERVICE","name":"app-config"}}},{"name":"MONGODB_URI","valueFrom":{"configMapKeyRef":{"key":"MONGODB_URI","name":"app-config"}}}],"image":"a7medayman6/e-voting-topics-service","name":"e-voting-topics-service","ports":[{"containerPort":3000}],"resources":{"limits":{"cpu":"100m","memory":"100Mi"},"requests":{"cpu":"100m","memory":"100Mi"}}}]}}}}
  creationTimestamp: "2023-08-31T18:39:04Z"
  generation: 1
  name: e-voting-topics-deployment
  namespace: default
  resourceVersion: "31834"
  uid: c7d8242d-bf1b-4dd4-aace-9c46f3dbce43
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: e-voting-topics-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: e-voting-topics-service
    spec:
      containers:
      - env:
        - name: TOPICS_SERVICE
          valueFrom:
            configMapKeyRef:
              key: TOPICS_SERVICE
              name: app-config
        - name: VOTING_SERVICE
          valueFrom:
            configMapKeyRef:
              key: VOTING_SERVICE
              name: app-config
        - name: VOTERS_SERVICE
          valueFrom:
            configMapKeyRef:
              key: VOTERS_SERVICE
              name: app-config
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              key: MONGODB_URI
              name: app-config
        image: a7medayman6/e-voting-topics-service
        imagePullPolicy: Always
        name: e-voting-topics-service
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-08-31T18:49:05Z"
    lastUpdateTime: "2023-08-31T18:49:05Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-08-31T18:39:04Z"
    lastUpdateTime: "2023-08-31T18:49:05Z"
    message: ReplicaSet "e-voting-topics-deployment-6444866967" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
