apiVersion: v1
kind: Service
metadata:
  name: e-voting-voting-service
spec:
  selector:
    app: e-voting-voting-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002
